[images]
remote_images = [
  "^(?:https:\\/\\/images\\.ctfassets\\.net(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$"
]

[build]
publish = ".next"
command = "npm run build: contentful && stackbit-build"
base = "/"
[build.environment]
  SENTRY_LOG_LEVEL = "debug"


[[plugins]]
package = "@netlify/plugin-nextjs"

  [plugins.inputs]

[[plugins]]
package = "@netlify/plugin-lighthouse"

[[plugins]]
package = "@sentry/netilfy-build-plugin"
[plugin.inputs]
org = "env:Cloud Perry"
project = "env:node"
AUTH_TOKEN = "emv: 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"
deploy = true
dryRun = true
[[redirects]]
from = "/_next/image"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200

  [redirects.query]
  url = ":url"
  w = ":width"
  q = ":quality"

[[redirects]]
from = "/_ipx/*"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200

  [redirects.query]
  url = ":url"
  w = ":width"
  q = ":quality"

[context]

  [context.production]

    [context.production.images]
    remote_images = [
      "^(?:https:\\/\\/images\\.ctfassets\\.net(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$"
    ]

  [context.main]

    [context.main.images]
    remote_images = [
      "^(?:https:\\/\\/images\\.ctfassets\\.net(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$"
    ]
