[build]
  base = "codo10"
  command = "cd codo10 && npm run build"
  publish = "codo10/.next"

[images]
  remote_images = [
    "^(?:https:\\/\\/images\\.ctfassets\\.net(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$"
  ]

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[redirects]]
  from = "/_next/image"
  to = "/.netlify/images?url=:url&w=:width&q=:quality"
  status = 200
    [redirects.query]
    url = ":url"
    w = ":width"
    q = ":quality"

[[redirects]]
  from = "/_ipx/*"
  to = "/.netlify/images?url=:url&w=:width&q=:quality"
  status = 200
  force = true
    [redirects.query]
    url = ":url"
    w = ":width"
    q = ":quality"

[context.production]
  [context.production.images]
    remote_images = [
      "^(?:https:\\/\\/images\\.ctfassets\\.net(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$"
    ]

[context.main]
  [context.main.images]
    remote_images = [
      "^(?:https:\\/\\/images\\.ctfassets\\.net(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$"
    ]
