[images]
remote_images = [
  "^(?:https:\\/\\/images\\.ctfassets\\.net(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$"
]

[build]
publish = ".next"
command = "npm run build"
base = "/"
[build.environment]
  SENTRY_LOG_LEVEL = "debug"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[plugins]]
package = "@netlify/plugin-lighthouse"

[[plugins]]
package = "@sentry/netlify-build-plugin"
  [plugins.inputs]
  sentryOrg = "cloud-perry"               # Replace with your Sentry organization slug
  sentryProject = "codo9"                 # Replace with your Sentry project slug
  sentryAuthToken = "${SENTRY_AUTH_TOKEN}" # Ensure this is configured in Netlify environment variables
  sentryRelease = "release-${DEPLOY_ID}" 
  sourceMapPath = ".next"                 # Path to source maps
  sourceMapUrlPrefix = "~/_next"          # Matches Next.js build directory structure
setCommits = true
  skipSetCommits = false
  skipSourceMaps = false
  deployPreviews = false

[[redirects]]
from = "/_next/image"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200

  [redirects.query]
  url = ":url"
  w = ":width"
  q = ":quality"

[[redirects]]
from = "/_ipx/*"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200

  [redirects.query]
  url = ":url"
  w = ":width"
  q = ":quality"

[context]

  [context.production]

    [context.production.images]
    remote_images = [
      "^(?:https:\\/\\/images\\.ctfassets\\.net(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$"
    ]

  [context.main]

    [context.main.images]
    remote_images = [
      "^(?:https:\\/\\/images\\.ctfassets\\.net(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$"
    ]
[build.environment]
SENTRY_LOG_LEVEL = "debug"
SENTRY_DEBUG = "true"
