backend:
  name: git-gateway
  branch: preview
media_folder: static/media
public_folder: /media
collections:
  - name: pages
    label: Pages
    folder: content/pages
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
